### ISSUE TITLE
目前什么进度啊，可有联系方式？

### ISSUE THREAD

**Issue by qcdong2016** [yenkeia/mirgo#1]
建议不要修改客户端代码，兼容官方的客户端

**Comment by yenkeia** [comment]
感谢 star 😄
目前进度做到了加载地图和怪物、NPC，人物可以在地图上跑。
联系方式的话目前先用 issue 吧，等我把功能完善得差不多了，关注的人也多了的时候我再弄个群。
修改客户端代码的原因有两个，一个是把一些我觉得没用的功能去掉方便开发，另一个是等以后有时间了我再慢慢汉化客户端。所以不打算兼容官方客户端了。

**Comment by qcdong2016** [comment]
可以pr ？

**Comment by yenkeia** [comment]
可以，欢迎👏

**Comment by qcdong2016** [comment]
搞个TODO，或者计划之类的。来一起完善。

**Comment by yenkeia** [comment]
ok 我尽快加上

**Comment by yenkeia** [comment]
开发计划加到 README 上了

**Comment by qcdong2016** [comment]
NPC脚本用lua实现吗？不兼容之前那种格式？

**Comment by yenkeia** [comment]
对，之前那种格式太复杂了我看不懂
反正要汉化，就直接 lua 吧

**Comment by qcdong2016** [comment]
他这个配置其实表达能力挺好的，用lua来做反而更像在写代码，而不是写配置。我试着照着他翻译了一种lua写法，反而没他那个易于理解
我看过一些老传奇，有一部分都用的这个格式。
![6F80E096-704A-4414-B56C-78E88C2F178F](https://user-images.githubusercontent.com/6292878/72871520-1fd00700-3d26-11ea-974d-b856061efbfb.png)
![BABE6012-7AFC-404B-8434-E5BB20C32284](https://user-images.githubusercontent.com/6292878/72871526-265e7e80-3d26-11ea-9248-43ec822d2074.png)

**Comment by qcdong2016** [comment]
大兄弟要不加个QQ。这聊天太费劲了。。以来一回就两天过去了。

**Comment by yenkeia** [comment]
![683F46FE-4386-4541-9FCD-207E58004183](https://user-images.githubusercontent.com/15378777/72872550-9bcb4e80-3d28-11ea-8005-3baef32737ef.jpeg)

好，老哥我建了个QQ群 32309474，群里聊吧
