### ISSUE TITLE
别的玩家装备显示不正确

### ISSUE THREAD

**Issue by yenkeia** [yenkeia/mirgo#45]
![image](https://user-images.githubusercontent.com/15378777/75767556-f58a5400-5d7d-11ea-8a16-79292318272d.png)

**Comment by qcdong2016** [comment]
和#46 一样 完善 RefreshEquipmentStats 函数就好了

**Comment by yenkeia** [comment]
fixed 2b2dddb68ef21b1b499fe14ec863e63b65993948
